-- 0028 was originally a seed of 6 legacy built-in executor configs into
-- executor_config (ADR-0008 move from DEFAULT_EXECUTORS → DB).
--
-- 2026-09-07 decision (specs/no-builtin-executor-seeding.md): do NOT seed any
-- built-in executor configs for the user. Configuration is user-owned;
-- "list = fact" only holds when every row was deliberately added.
--
-- This file is intentionally a no-op:
--   - Fresh installs: executor_config stays empty (0 rows after all migrations).
--   - Existing installs: 0028 already applied historically, so drizzle will
--     never re-run it; user-edited rows stay exactly as they are (R2 hard
--     constraint). Drizzle advances by journal `when` / created_at only and
--     does not re-validate hashes of already-applied migrations, so turning
--     the body into a no-op is safe for upgrades.
--
-- The `reviewer` entry was never part of this seed (cleared separately in 0029).
--
-- Keep the filename/tag stable so journal idx 28 stays continuous.
SELECT 1 WHERE false;
